package com.rtumirea.KazakovIG.cursework.domain.enums;

public enum ServiceType {
    MAINTENANCE,
    DIAGNOSTICS,
    TRANSMISSION_REPAIR,
    ENGINE_REPAIR,
    DIESEL_ENGINE_REPAIR,
    ELECTRICAL_EQUIPMENT_REPAIR,
    SUSPENSION_REPAIR,
    STEERING_REPAIR,
    BRAKE_SYSTEM_REPAIR,
    BODY_PAINTING,
    DETAILING,
    BODYWORK_REPAIR,
    GLASS_REPLACEMENT

}
